services:
  datasource:
    container_name: karto-db
    image: postgres:latest
    env_file:
      - infrastructure.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - karto
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: karto-keycloack
    image: quay.io/keycloak/keycloak:26.2
    env_file:
      - infrastructure.env
    ports:
      - "7080:7080"
    networks:
      - karto
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start-dev", "--http-port", "7080", "--https-port", "7443" ]

  mailpit:
    container_name: karto-mailpit
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - karto
    restart: unless-stopped
    volumes:
      - ./data:/data

networks:
  karto:
    driver: bridge

volumes:
  postgres:
  pgadmin: